import * as mongoose from 'mongoose';

const Schema = mongoose.Schema;

export const AparatologiaSchema = new Schema({
    create_date: { type: Date },
    hora_aplicacion: { type: Date },
    fecha_hora: { type: Date },
    paciente: { type: Schema.ObjectId, ref: 'Paciente' },
    cita: { type: Schema.ObjectId, ref: 'Cita' },
    dermatologo: { type: Schema.ObjectId, ref: 'Empleado' },
    servicio: { type: Schema.ObjectId, ref: 'Servicio' },
    tratamientos: [{}],
    areas: [{ type: Schema.ObjectId, ref: 'Area' }],
    numero_sesion: { type: String },
    quien_agenda: { type: Schema.ObjectId, ref: 'Empleado' },
    tipo_cita: { type: Schema.ObjectId, ref: 'TipoCita' },
    medio: { type: Schema.ObjectId, ref: 'Medio' },
    quien_confirma_llamada: { type: Schema.ObjectId, ref: 'Empleado' },
    quien_confirma_asistencia: { type: Schema.ObjectId, ref: 'Empleado' },
    status: { type: Schema.ObjectId, ref: 'Status' },
    motivos: { type: String },
    precio: { type: String },
    pago_dermatologo: { type: String },
    tiempo: { type: String },
    observaciones: { type: String },
    sucursal: { type: Schema.ObjectId, ref: 'Sucursal' },
    promovendedor: { type: Schema.ObjectId, ref: 'Empleado' },
    cosmetologa: { type: Schema.ObjectId, ref: 'Empleado' },
    hora_llegada: { type: String },
    hora_atencion: { type: String },
    hora_salida: { type: String },
    pagado: { type: Boolean, default: false },
    factura: { type: Schema.ObjectId, ref: 'Factura' },
    pagos: [{ type: Schema.ObjectId, ref: 'Pago' }],
    consecutivo: { type: Number },
    consulta: { type: Schema.ObjectId, ref: 'Consulta' },
    producto: { type: Schema.ObjectId, ref: 'Producto' },
    frecuencia: { type: Schema.ObjectId, ref: 'Frecuencia' },
});