import * as mongoose from 'mongoose';

const Schema = mongoose.Schema;

export const EsteticaSchema = new Schema({
    create_date: { type: Date },
    hora_aplicacion: { type: Date },
    fecha_hora: { type: Date },
    consulta: { type: Schema.ObjectId, ref: 'Consulta' },
    paciente: { type: Schema.ObjectId, ref: 'Paciente' },
    dermatologo: { type: Schema.ObjectId, ref: 'Empleado' },
    quien_agenda: { type: Schema.ObjectId, ref: 'Empleado' },
    quien_confirma: { type: Schema.ObjectId, ref: 'Empleado' },
    sucursal: { type: Schema.ObjectId, ref: 'Sucursal' },
    tipo_cita: { type: Schema.ObjectId, ref: 'TipoCita' },
    consecutivo: { type: Number },
    pagado: { type: Boolean, default: false },
    hora_llegada: { type: String },
    hora_atencion: { type: String },
    hora_salida: { type: String },
    precio: { type: String },
    total: { type: String },
    pago_dermatologo: { type: String },
    materiales: [],
    toxinas_rellenos: [],
    status: { type: Schema.ObjectId, ref: 'Status' },
    servicio: { type: Schema.ObjectId, ref: 'Servicio' },
    factura: { type: Schema.ObjectId, ref: 'Factura' },
    pagos: [{ type: Schema.ObjectId, ref: 'Pago' }],
    producto: { type: Schema.ObjectId, ref: 'Producto' },
    frecuencia: { type: Schema.ObjectId, ref: 'Frecuencia' },
    total_aplicacion: { type: String },
    porcentaje_descuento_clinica: { type: String },
    has_descuento_dermatologo: { type: Boolean, default: false },
    descuento_clinica: { type: String },
    descuento_dermatologo: { type: String },
});
