import { PacienteI } from "./paciente.interface";
import { SucursalI } from "./sucursal.interface";
import { EmpleadoI } from "./empleado.interface";
import { TipoCitaI } from "./tipo-cita.interface";
import { StatusI } from "./status.interface";
import { ServicioI } from "./servicio.interface";
import { PagoI } from "./pago.interface";
import { AreaI } from "./area.interface";
import { MedioI } from "./medio.interface";
import { ConsultaI } from "./consulta.interface";
import { ProductoI } from "./producto.interface";
import { FrecuenciaI } from "./frecuencia.interface";
import { FacturaI } from "./factura.interface";

export interface DermapenI {
    create_date: Date;
    hora_aplicacion: Date;
    fecha_hora: Date;
    paciente: PacienteI;
    consulta: ConsultaI;
    dermatologo: EmpleadoI;
    servicio: ServicioI;
    tratamientos: [];
    areas: AreaI[];
    quien_agenda: EmpleadoI;
    tipo_cita: TipoCitaI;
    medio: MedioI;
    quien_confirma_llamada: EmpleadoI;
    quien_confirma_asistencia: EmpleadoI;
    status: StatusI;
    motivos: String;
    precio: String;
    pago_dermatologo: String;
    costo: String;
    total: String;
    tiempo: String;
    observaciones: String;
    sucursal: SucursalI;
    promovendedor: EmpleadoI;
    hora_llegada: String;
    hora_atencion: String;
    hora_salida: String;
    pagado: Boolean;
    factura: FacturaI;
    pagos: PagoI[];
    materiales: [];
    consecutivo: Number;
    producto: ProductoI;
    frecuencia : FrecuenciaI;
}